# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"

  config.vm.network "private_network", ip: "10.0.0.100"
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.synced_folder "../build/", "/srv/build/", type: "nfs"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
end
