#!/bin/bash

LISTUTIL=$(which git-subrepo-list 2>/dev/null)

if [ -z "$LISTUTIL" ]
then
  echo "error: couldn't find git-subrepo-list utility in $PATH"
  exit
fi

REPOS=($($LISTUTIL))

if [ ${#REPOS[@]} != 0 ]
then
  for REPO in ${REPOS[@]}
  do
    cd $REPO

    if ! [[ $(git status) =~ .*nothing\ to\ commit.* ]]
    then
      echo "$REPO (changed)"
    fi

    cd - > /dev/null
  done
fi
