#!/bin/bash

echo "Finding sub-folder git repositories..."

repos=($(find ./* -name ".git" | cut -c 3-))
n_repos=${#repos[@]}

if [ $n_repos = 0 ]
then
  echo "No repositories were found."
else
  echo -e "Checking status of ${n_repos} repositories...\n"
  changed=0

  for i in "${repos[@]}"
  do
    cd "$i/.."

    if ! [[ $(git status) =~ .*nothing\ to\ commit.* ]]
    then
      let "changed += 1"
      echo "Changed: ${PWD}"
    fi

    cd - > /dev/null
  done

  if [ $changed != 0 ]
  then
    echo -e "\n$changed repositories have changed."
  else
    echo "Nothing changed."
  fi
fi
